---
- name: abonaparte | Add abonaparte as sudo user
  become: yes
  user:
    name: "{{ uusername }}"
    password: "{{ upassword | password_hash('sha512') }}"
    groups: admin
    comment: Arron Bonaparte
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
