---
- name: apt | Install applications
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - tree
    - git
    - python-pip
    - python-dev
    - build-essential

